### ISSUE TITLE
download artifact matching pattern

### ISSUE THREAD

**Issue by igagis** [actions/download-artifact#103]
Currently it is only possible to download all artifacts or one artifacts.

Need to add possibility to download several artifacts whose name matches given pattern.

**Comment by csmart894** [comment]
Green

**Comment by alessandro505** [comment]
???

**Comment by aparcar** [comment]
This doesn't look very dynamic, could this please become a feature?

**Comment by da1910** [comment]
This affects us also, we use tox to run python tests against several different versions of python, these need to be collected and it would be much better to say

`    - uses: actions/download-artifact@v2
      with:
        name: coverage-*
        path: ~/coverage-reports`

Rather than either manually specifying all the names, or getting every artifact from this run.

**Comment by rohit-gohri** [comment]
We also upload a build artifact, test reports and coverage reports. In the end we want to download the coverage reports to merge them, but it ends up downloading the build artifact which adds an unnecessary 30 seconds to the build

**Comment by TWiStErRob** [comment]
Just as an example this is how it looks when I have to maintain without patterns:
https://github.com/TWiStErRob/net.twisterrob.gradle/pull/219/files#diff-3ab46ee209a127470fce3c2cf106b1a1dbadbb929a4b5b13656a4bc4ce19c0b8R715-R809

**Comment by AL1000043** [comment]
Hello everyone, this could be a useful feature for us too

**Comment by dmitry-stepanenko** [comment]
I was able to use the workaround for this limitation by picking only desired artifacts after they're downloaded. Using rsync it's possible to pick certain artifacts using specific mask and merge them into 1 folder 

```yml

      - name: Upload reports' artifacts
        # Contrary to "if: always()", "if: success() || failure()" keeps the ability to cancel builds
        if: (success() || failure())
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_artifact_${{ env.RUN_UNIQUE_ID }}_${{ matrix.step }}
          if-no-files-found: ignore
          path: reports
          retention-days: 1

      # downloading them later
      - name: Download reports' artifacts
        uses: actions/download-artifact@v3
        with:
          path: downloaded_artifacts
      - name: Place reports' artifacts
        if: steps.check_files.outputs.files_exists == 'true'
        run: rsync -av downloaded_artifacts/unit_test_artifact_${{ env.RUN_UNIQUE_ID }}_*/*/ unit_test_reports/
      - run: ls -R unit_test_reports

```
