### ISSUE TITLE
[bug] Error: Unable to find any artifacts for the associated workflow

### ISSUE THREAD

**Issue by David-Lor** [actions/download-artifact#124]
### What happened?

- I'm trying the following workflow, with a download-artifact action in it: https://github.com/David-Lor/Docker-Python-Git-App/blob/feature/build-if-base-image-changes/.github/workflows/build_test_push.yaml
- The requested Artifact name exists on the workflow running
- The repository is public
- The only thing "special" I can think about is that I'm running the workflow from a branch different than the default, so I guess the artifacts get stored on that branch. Maybe the download-artifact action is trying to fetch the Artifact from the default branch?

Error from download-artifact action:
![imagen](https://user-images.githubusercontent.com/17401854/145244125-a9d5db73-278e-4efb-9030-1ef03169b34b.png)

### What did you expect to happen?

The Artifact to be downloaded.

An Artifact with the requested name exists for the running workflow:
![imagen](https://user-images.githubusercontent.com/17401854/145244258-ff67bd6e-a05e-4b97-a3c0-4e334e1da216.png)

### How can we reproduce it?

The workflow is quite complex: https://github.com/David-Lor/Docker-Python-Git-App/blob/feature/build-if-base-image-changes/.github/workflows/build_test_push.yaml

However, I started by trying this sample workflow in a private repository, with the same bad results (I though it may be a problem caused by running the Action from a private repository, that's why I tried on my public repository, which is where I want to finally use it).

```yaml
name: "Read & Persist Artifact"
on:
  workflow_dispatch: {}

jobs:
  ReadPersistArtifact:
    name: "Read & Persist Artifact"
    runs-on: "ubuntu-latest"
    env:
      artifactName: "my-artifact-2"
      artifactPath: "./artifacts"
      artifactFile: "artifact-file.txt"

    steps:
      - name: "Create artifact directory"
        run: |-
          mkdir ${{ env.artifactPath }}
      - name: "Get artifact"
        uses: "actions/download-artifact@v2"
        continue-on-error: true
        with:
          name: "${{ env.artifactName }}"
          path: "${{ env.artifactPath }}"
      - name: "Set Artifact acquired flag"
        run: |-
          cat "${{ env.artifactPath }}/${{ env.artifactName }}" && echo "actifactRead=true" >> $GITHUB_ENV || echo "artifactRead=false" >> $GITHUB_ENV
      - name: "Show artifact content"
        if: "${{ env.artifactRead == 'true' }}"
        working-directory: "${{ env.artifactPath }}"
        run: |-
          pwd
          ls -lah .
          echo "Read artifact file content:"
          cat ${{ env.artifactFile }}
      - name: "Write artifact (append line)"
        working-directory: "${{ env.artifactPath }}"
        run: |-
          pwd
          echo "$(date)" >> ${{ env.artifactFile }}
          ls -lah .
          echo "Written artifact file content:"
          cat ${{ env.artifactFile }}
      - name: "Upload artifact"
        uses: "actions/upload-artifact@v2"
        with:
          name: "${{ env.artifactName }}"
          path: "${{ env.artifactPath }}/${{ env.artifactFile }}"
          retention-days: 1
```

In this case, artifact exists from a previous run:
![imagen](https://user-images.githubusercontent.com/17401854/145244863-c7f7679f-5a5b-42bb-b819-8d4cc018e75c.png)

But is not found on the next run:
![imagen](https://user-images.githubusercontent.com/17401854/145244937-2783d10f-c5d2-43d3-b90e-760de72a5e44.png)

### What version of the action are you using?

v2

### What are your runner environments?

linux
