### ISSUE TITLE
[bug] env vars do not get resolved

### ISSUE THREAD

**Issue by jelmd** [actions/download-artifact#125]
### What happened?

Unfortunately download-artifact does not resolve env vars, which makes it pretty useless.

### What did you expect to happen?

path and names should accept env.vars [and a big+ would be to be able to mangle names, i.e. replaceAll("foo", "o", "bar") or something like that, or is there any way to modify vars before passing them to `uses`?].

### How can we reproduce it?

```
jobs:
  job_1:
    name: Stack
    runs-on: ubuntu-18.04
    steps:
      - name: Download stack
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.GITHUB_REPOSITORY }}-stack.tgz
          path: /var/tmp/${{ GITHUB_REPOSITORY}}
```

Have a look at the logs: it just say `-stack.tgz` and `/var/tmp/`

### What version of the action are you using?

actions/download-artifact@v2

### What are your runner environments?

linux

### Are you on GitHub Enterprise Server? If so, what version?

github.com
