### ISSUE TITLE
[bug] Folder duplication when Downloading Artifacts

### ISSUE THREAD

**Issue by ferasallaou** [actions/download-artifact#126]
### What happened?

I've multiple jobs in my workflow, one of them will upload all the artifacts, total of 4, and the name of the file would be graphql for example. When I download this artifact to my machine, I extract it and get a folder named graphql and inside it two js files. 
However, in my second job, when I use download-artifact action, it downloads all the artifacts without an issue to a specific path `tmp` but when I navigate inside that path, I find a new folder called graphql, which is normal, but then inside it another folder called graphql which contains the two js files, so there is two folders called graphql for no reason.
Here is my uploading code
```
      - name: Upload code artifact
        uses: actions/upload-artifact@v2
        with:
            name: ${{env.ARTIFACT_FILENAME}}
            path: dist/apps
            if-no-files-found: error
```
where filename would be graphql, webhooks and so on. and here is my download code
```
    - name: Download Artifacts & Merge in One
        if: "!!steps.release.outputs.version"
        uses: actions/download-artifact@v2
        with:
          path: tmp/

      - name: Check Artifacts
        run: |
          pwd && ls -laF tmp
          cd tmp/graphql && ls -laF
```
and the output will be 
```
/home/runner/work/app/
total 24
drwxr-xr-x  6 runner docker 4096 Dec 24 14:52 ./
drwxr-xr-x 13 runner docker 4096 Dec 24 14:52 ../
drwxr-xr-x  3 runner docker 4096 Dec 24 14:52 graphql/
drwxr-xr-x  3 runner docker 4096 Dec 24 14:52 webhooks/
total 12
drwxr-xr-x 3 runner docker 4096 Dec 24 14:52 ./
drwxr-xr-x 6 runner docker 4096 Dec 24 14:52 ../
drwxr-xr-x 2 runner docker 4096 Dec 24 14:52 graphql/
```

### What did you expect to happen?

the output of 
```
    - name: Download Artifacts & Merge in One
        if: "!!steps.release.outputs.version"
        uses: actions/download-artifact@v2
        with:
          path: tmp/

      - name: Check Artifacts
        run: |
          pwd && ls -laF tmp
          cd tmp/graphql && ls -laF
```
should be
```
/home/runner/work/app/
total 24
drwxr-xr-x  6 runner docker 4096 Dec 24 14:52 ./
drwxr-xr-x 13 runner docker 4096 Dec 24 14:52 ../
drwxr-xr-x  3 runner docker 4096 Dec 24 14:52 graphql/
drwxr-xr-x  3 runner docker 4096 Dec 24 14:52 webhooks/
total 12
drwxr-xr-x 3 runner docker 4096 Dec 24 14:52 ./
drwxr-xr-x 6 runner docker 4096 Dec 24 14:52 ../
drwxr-xr-x 2 runner docker 4096 Dec 24 14:52 index.map.js
drwxr-xr-x 2 runner docker 4096 Dec 24 14:52 index.js

```

### How can we reproduce it?

Upload a folder using upload-artifact and then download it back again using download-artifact

### What version of the action are you using?

V2

### What are your runner environments?

linux
