### ISSUE TITLE
[feat req] Add optional parameters for owner, repo, and run_id

### ISSUE THREAD

**Issue by aebrahim** [actions/download-artifact#130]
### What would you like to be added?

It would be fantastic if the action took these additional parameters to quickly download artifacts from other runs.

Currently, implementing https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ is really cumbersome, with a lot of custom code needed. This would really simplify it:

```yaml
on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed
 jobs:
  upload:
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact
          run_id: ${{ github.event.workflow_run.id }}
```

### Why is this needed?

Doing the secure thing should be the easy thing, and a plug-and-play action to work around a security vulnerability is a lot better than a 20 line block of code to copy paste. Additionally, I believe adding these features will resolve #3.
