### ISSUE TITLE
outputs.download-path is a local directory when running on self-hosted [bug]

### ISSUE THREAD

**Issue by JulianBissekkou** [actions/download-artifact#135]
### What happened?

I am using a self-hosted mac os runner for building a macOS app. When the build is done, the artifact is uploaded and the download URL is then shared by a Slack bot that notifies the team about the version that was built.

I download the artifact:

```
    - uses: actions/download-artifact@v2
        id: mac-download
        with:
          name: my_tool
          path: my_tool/PublishingTool.zip

      - name: 'Send message via slack'
        env:
          MAC_URL: ${{ steps.mac-download.outputs.download-path }}
        run:  run notify-slack.sh --mac-app=$MAC_URL
```

### What did you expect to happen?

I expect `MAC_URL` to be a https url to the artifact that I uploaded. Instead, I get the local path of my runner.
`/Users/ci-mac/project/somefile.zip`

### How can we reproduce it?

Upload an asset using `actions/upload-artifact@v2` then download this asset using `actions/download-artifact@v2` and access `outputs.download-path` of the step as described in the readme.

### What version of the action are you using?

actions/download-artifact@v2

### What are your runner environments?

self-hosted, macos
