### ISSUE TITLE
[bug] Error: An error occurred while attempting to decompress the response stream

### ISSUE THREAD

**Issue by cytopia** [actions/download-artifact#151]
### What happened?

Error: An error occurred while attempting to decompress the response stream
A 200 response code has been received while attempting to download an artifact

### What did you expect to happen?

A normal download

### How can we reproduce it?

Have a matrix build of ~30 jobs, where each job uploads an artifact (~ 100MB) (all unique names)
Have another matrix build (same number of jobs) where each job downloads their corresponding artifact.

I ususally always get one of the download jobs to fail with:

Error: An error occurred while attempting to decompress the response stream
A 200 response code has been received while attempting to download an artifact

### Anything else we need to know?

I have additionally wrapped everything into an external retry action to see if it helped:
```
      - name: "[Artifact Load] Download base"
        uses: Wandalen/wretry.action@v1.0.11
        with:
          action: actions/download-artifact@v3
          with: |
            name: ${{ steps.set-artifact-name.outputs.base }}
          attempt_limit: 20
          attempt_delay: 10000
```
But it did not help, the error kept occuring

### What version of the action are you using?

v3

### What are your runner environments?

linux
