### ISSUE TITLE
HTML reports is broken when its downloaded from github action using github artifact

### ISSUE THREAD

**Issue by VaghasiyaKrupal** [actions/download-artifact#155]
### What happened?

I am running my test into GitHub action and after test execution is completed I download generated report using `github/action-artifact` and when I open that report design is broken.

### What did you expect to happen?

It should show the original design. like the below image.

![image](https://user-images.githubusercontent.com/45596703/164882851-06363c30-78bd-4ffd-a084-cab4a99898a6.png)

### How can we reproduce it?

```
name: Legrande GitHub Actions
on:
#   schedule:
#   - cron: "0 0 * * *"

  push:
    branches:
      - 'master'

jobs:
 seleniumPython-test:
  name: Run on Linux
  runs-on: ubuntu-20.04

  steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      continue-on-error: true
      run: |
        py.test --html=report.html -v testCases/Master.py

    - name: make public directory
      run: |
        mkdir public
        cp -r report.html public/report.html

    - name: download artifact
      uses: actions/upload-artifact@v2
      with:
        name: Download-reports
        path: report.html

    - name: Deploy reports
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
```

This is my `workflow` file

### Anything else we need to know?

This is what I am getting when downloading reports from GitHub action using `artifact`

![Cw79v](https://user-images.githubusercontent.com/45596703/164882956-7ad26176-0752-4b9e-ad11-a241e254aad1.png)

### What version of the action are you using?

v2

### What are your runner environments?

linux
