### ISSUE TITLE
[bug] v3 download-artifact with name specified still creates folder

### ISSUE THREAD

**Issue by jprecuch** [actions/download-artifact#159]
### What happened?

Based on readme following should apply
With v2 and v3, when an artifact is specified by the name input, there is no longer an extra directory that is created if the path input is not provided. All the contents are downloaded to the current working directory.
```
   current/working/directory/
      ... contents of my-artifact
```
When I however configured download artifact like this:
```
      - name: Download new manifest artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.create_required_variables.outputs.artifact-prefix }}
```
I can still see the additional directory is being created
```
Artifact 05-26-2022-150933-manifests was downloaded to /__w/my-repo/my-repo/05-26-2022-150933-manifests
```

The artifact was created by following:
```
      - name: Create new manifest artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.current-date.outputs.current-date }}-manifests
          path: ./*/manifests/
          retention-days: 1
```

Can you please check why this happen and if this expected scenario?
Is there some way how to get rid of that additional directory of name of artifact?

### What did you expect to happen?

There should be no additional directory created based on README

### How can we reproduce it?

See the description

### What version of the action are you using?

v3

### What are your runner environments?

self-hosted
