### ISSUE TITLE
Fails to download artifact that hasn't yet been uploaded

### ISSUE THREAD

**Issue by aidansteele** [actions/download-artifact#16]
My workflow has two jobs that run in parallel. Job A, the artifact uploader, takes about ~40 seconds before it gets to the `actions/upload-artifact` step. Job B, the artifact downloader, takes about ~20 seconds before it gets to the `actions/download-artifact` step. It fails immediately with this error:

> Downloading artifact 'frontend' to: '/home/runner/work/sshst/sshst/pubsite/build'
> ##[error]An Artifact with name "frontend" was not found.
> ##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.163.1/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.DownloadArtifact, Runner.Plugins"'.

If I put a step with `sleep 60` before the download step, it works great! My initial assumption was that the `actions/download-artifact` action would wait until the corresponding `actions/upload-artifact` step succeeds/fails before attempting to download.

Is this behaving as intended? Do you see value in adding that functionality? Alternatively, is there a better workaround than `sleep`?

Thanks!

**Comment by marph91** [comment]
You could try to add `needs: Job A` in the configuration of Job B. This should start Job B only when Job A was finished. See also [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idneeds).

**Comment by aidansteele** [comment]
@marph91 That's an _ok_ workaround, but in my case there are a lot of slow steps in Job A that happen after the artifact is uploaded. It would be great if Job B didn't have to wait for those steps

**Comment by konradpabjan** [comment]
@aidansteele Maybe splitting up into 3 jobs? That's about the only thing I can suggest. The `download-action` first gets a list of available artifacts and then if the artifact is available, proceeds to download it. I don't see us ever adding support for something like timeouts/sleeping or waiting for an artifact to be available directly in the action.

```
jobs:
  A:
    runs-on: ubuntu-latest
    steps:
    ....
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: path
  B:
    runs-on: ubuntu-latest
    needs: A
    steps:
    ....
    # other long running steps 
  C:
    runs-on: ubuntu-latest
    needs: A
    steps:
    ....
    - name: Download
      uses: actions/download-artifact@v1
      with:
        name: output
```
