### ISSUE TITLE
[feat req] v4 abandon name

### ISSUE THREAD

**Issue by abitrolly** [actions/download-artifact#166]
### What would you like to be added?

Currently, if "name" is not specified, the action creates additional dirs when unpacking files. So when you upload a file like this.

```yaml
- uses: actions/upload-artifact@v3
  with:
    path: path/to/artifact/world.txt
```
And then download like this,
```yaml
- uses: actions/download-artifact@v3
```
You will get `artifact/world.txt` instead of `world.txt` in current dir.

I propose simplified the logic for v4 for both upload and download, so that adding and extracting files had a predictable behavior, just like working with standard archives.

```
- uses: actions/upload-artifact@v4
  with:
    pathroot: path/to/artifact
    filefilter: world.txt
    archroot: docs
```

```
- uses: actions/download-artifact@v4
  with:
    pathroot: dist
    filefilter: docs/world.txt
```

These two actions pass `path/to/artifact/world.txt` from one job to `dist/docs/world.txt` in another.

So subdirs are used explicitly to separate files from different jobs in one run. Instead of artifact name, as it is now. Which is sometimes prepended to output dir and sometimes not.

The same filters are used for both compressing and extracting logic. This avoids tracking where magic pattern ends, to understand where your files will get at.

The default behavior for overwriting files that are already present would be to fail, unless `overwrite: true` is set.

### Why is this needed?

Learning upload/download path handling is hard. Usually it requires a few manual CI runs. Normalizing logic to be similar with how users work with archives will help more people get this right from the first try (and understand what is going on in terms of errors). This could be immediately solve #103, #165, #138, #105, and well, perhaps some of the older issues that may have been already addressed by v2 and v3.
