### ISSUE TITLE
path example bug

### ISSUE THREAD

**Issue by gregersrygg** [actions/download-artifact#17]
I was having trouble understanding the path option and suspecting the example was incorrect. So I tried runnin the example code from upload-artifact and download-artifact in a workflow. The example for the `path` option returns with an error:

    cat: path/to/artifact: Is a directory

Here is the example from the readme:

```yaml
steps:
- uses: actions/checkout@v1

- uses: actions/download-artifact@v1
  with:
    name: my-artifact
    path: path/to/artifact
    
- run: cat path/to/artifact
```

Assuming the example is using the artifact from the [upload-artifact](https://github.com/actions/upload-artifact) example (should probably be stated explicitly in the readme), I think the `run` step should be:

```yaml
- run: cat path/to/artifact/world.txt
```

This bug caused a lot of confusion for me, since I assumed the downloaded artifact would be stored in the folder `path/to` and the file in the artifact named `artifact` instead of the original filename.
