### ISSUE TITLE
Allow downloading artifacts cross-workflow

### ISSUE THREAD

**Issue by CAD97** [actions/download-artifact#172]
### What would you like to be added?

Allow specifying a workflow run id from which to download the artifact(s).

Blocked on `@actions/artifact` exposing this functionality:

- https://github.com/actions/toolkit/issues/1141

**Example**

```yaml
on:
  workflow_run:
    types: [completed]

steps:
- uses: actions/checkout@v2
- uses: actions/download-artifact@v3
  with:
    name: my-artifact
    path: path/to/artifact
    run-id: ${{ github.event.workflow_run.id }}
- name: Display structure of downloaded files
  run: ls -R
  working-directory: path/to/artifact
```

### Why is this needed?

To make [preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) a lot more tractable.

Specifically, `pull_request` workflows should have read-only token permissions; this cap *cannot* be lifted for `${{ github.token }}`. For cases where you want to perform privileged actions based on the result of testing unprivileged code (anything requiring write permission, e.g. leave a comment, add check annotations, etc), the suggested pattern is to upload an artifact containing the collected information from the unprivileged run and download it from a privileged `workflow_run` follow-up which does the privileged actions based on that information.

Currently this requires using the `gh` CLI, `actions/github-script`'s `octokit`, or some other way of downloading the artifact from the REST API such as [dawidd6/action-download-artifact](https://github.com/dawidd6/action-download-artifact). This should be achievable with just `actions/download-artifact`.

This does not replace the 3rd party actions. `actions/download-artifact` *only* should support downloading from a specified workflow run id (which defaults to this workflow run if unspecified), whereas the 3rd party actions all support more involved ways of finding the workflow run to download from.
