### ISSUE TITLE
[bug] Warning in workflow about set-output

### ISSUE THREAD

**Issue by mrgharabaghi** [actions/download-artifact#185]
### What happened?

Warning: `The "set-output" command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

### What did you expect to happen?

Downloading the artifact without deprecation warning.

### How can we reproduce it?

```yml
on: push
jobs:
  build-node:
    runs-on: ubuntu-22.04
    container: node:18
    steps:
      # -----------------------------------------------
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3 # uses
      - run: npm i
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      # -----------------------------------------------
      - name: Copy File
        working-directory: work
        run: |
          npm i
          npm run build
      # -----------------------------------------------
      - uses: actions/upload-artifact@v3 # uses
        with:
          name: my-artifact-1
          path: path/to/artifact/world.txt
          retention-days: 1
      # -----------------------------------------------
      - uses: actions/upload-artifact@v3 # uses
        with:
          name: my-artifact-2
          path: work/built
          retention-days: 1
      # -----------------------------------------------
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      # -----------------------------------------------
      - name: Display structure of downloaded files
        run: |
          tar -C ./my-artifact-1 -cvf my-artifact-1.tar.gz .
          tar -C ./my-artifact-2 -cvf my-artifact-2.tar.gz .
```

### What version of the action are you using?

v3.0.0

### What are your runner environments?

linux
