### ISSUE TITLE
[Bug] Specific artifact downloads result in broken downloads when a path isn't specified

### ISSUE THREAD

**Issue by L1ghtmann** [actions/download-artifact#191]
### What happened?

Downloading a specific artifact without a `path` appears to result in a broken download. 

When downloading all artifacts, a `path` is optional and if it is not passed the artifact downloads appear in the $PWD as expected. When downloading a specific artifact, however, not providing a `path` results in a broken download. Based on the README, this seems like unintended behavior. 

### What did you expect to happen?

The specific artifact download to be valid (i.e., download to the $PWD and have valid contents).

### How can we reproduce it?

1. Upload an artifact (using a specific container name)
2. Download the specific artifact (using the specific container name from 1)
3. Observe how the contents of the artifact within its container are not accessible as expected

### Anything else we need to know?

Specific download w/o a path:
```yml
- name: Download artifacts
  uses: actions/download-artifact@main
  with:
      name: package
```
![pre](https://user-images.githubusercontent.com/67040127/201375565-7a83e878-cb18-4182-b68a-b8fdd414af4f.png)

Specific download w/ a path:
```yml
- name: Download artifacts
  uses: actions/download-artifact@main
  with:
      name: package
      path: ~/package
```
![post](https://user-images.githubusercontent.com/67040127/201376056-c15378f6-ee57-4920-8827-085d136baa3f.png)

All download w/o a path:
```yml
- name: Download artifacts
  uses: actions/download-artifact@main
```
![all](https://user-images.githubusercontent.com/67040127/201376385-e53080d6-be9e-485c-b70e-0f87ddbb1a47.png)

### What version of the action are you using?

v3.0.1

### What are your runner environments?

linux, macos
