### ISSUE TITLE
[bug] Permission denied when downloading file

### ISSUE THREAD

**Issue by thiagowig** [actions/download-artifact#203]
### What happened?

I'm getting the following error when trying to download files using download-artifact action:

```
Starting download for test.txt
Directory structure has been setup for the artifact
Total number of files that will be downloaded: 102
Total file count: 102 ---- Processed file #23 (22.5%)
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/home/runner/work/cari-mono/cari-mono/.git/objects/00/e7[6](https://github.com/thiagowig/cari-mono/actions/runs/4198924337/jobs/7283174105#step:4:7)c[7](https://github.com/thiagowig/cari-mono/actions/runs/4198924337/jobs/7283174105#step:4:8)dd466b5e20bb977c29bc[8](https://github.com/thiagowig/cari-mono/actions/runs/4198924337/jobs/7283174105#step:4:9)[9](https://github.com/thiagowig/cari-mono/actions/runs/4198924337/jobs/7283174105#step:4:10)60c420c87[10](https://github.com/thiagowig/cari-mono/actions/runs/4198924337/jobs/7283174105#step:4:11)'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:[12](https://github.com/thiagowig/cari-mono/actions/runs/4198924337/jobs/7283174105#step:4:13)2:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -[13](https://github.com/thiagowig/cari-mono/actions/runs/4198924337/jobs/7283174105#step:4:14),
  code: 'EACCES',
  syscall: 'open',
  path: '/home/runner/work/cari-mono/cari-mono/.git/objects/00/e76c7dd466b5e[20](https://github.com/thiagowig/cari-mono/actions/runs/4198924337/jobs/7283174105#step:4:21)bb977c29bc8960c420c8710'
}
```

### What did you expect to happen?

It's expected to download file properly

### How can we reproduce it?

Using the following workflow:

```
name: Testing bug

on: [push]

jobs:
  bug-test:
    runs-on: ubuntu-latest

    steps:
      - name: clone-application
        uses: actions/checkout@v3

      - name: artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: test.txt
          path: .

      - name: artifact download
        uses: actions/download-artifact@v3
        with:
          name: test.txt
          path: .
```

### What version of the action are you using?

v3

### What are your runner environments?

linux

**Comment by cablespaghetti** [comment]
We have just upgraded to self hosted Ubuntu 22.04 based runners from 20.04 and have started getting this error. I suspect it might be related to that.

**Comment by cablespaghetti** [comment]
Ok I think I've found our issue. We moved from a runner based on:
* https://github.com/actions/actions-runner-controller/blob/master/runner/actions-runner-dind.ubuntu-20.04.dockerfile with UID 1000 and GID 1001
to
* https://github.com/actions/actions-runner-controller/blob/master/runner/actions-runner-dind.ubuntu-22.04.dockerfile with UID 1001 and GID 121

This works fine except when our workflow brings in jobs using our own separate containers using UID 1000 because the artifact now has files owned by a different UID due to the newer image.

I think this will also occur with github-hosted runners, as they use UID 1001 unlike our old image.

More information: https://github.com/actions/actions-runner-controller/pull/1688

**Comment by kfird214** [comment]
Having the same issue, Is there any update on this?

**Comment by thecesrom** [comment]
I had the same problem and fixed it by removing the `.git` directory.

```yml
- uses: actions/upload-artifact@v4
  with:
    name: my-artifact
    path: |
      ${{ github.workspace }}
      !.git/
```

For this action, `name` is the name of the artifact, not the name of the file. To upload the `test.txt` file, you should use the `path` argument.

```yml
- uses: actions/upload-artifact@v4
  with:
    name: my-artifact
    path: test.txt
```

Hope this helps.
