### ISSUE TITLE
[feat req] Downloading a list of artifacts?

### ISSUE THREAD

**Issue by tschm** [actions/download-artifact#216]
### What would you like to be added?

I would love to do stuff like

```
# Download all artifacts
      - uses: actions/download-artifact@v3
        with:
          name: [sphinx, test]
          path: .book/artifacts
```

### Why is this needed?

I can either download one artifact or all artifact. Maybe you support already an explicit list given by the user. Would be more robust.
