### ISSUE TITLE
[bug] download-path output not specified in action.yaml

### ISSUE THREAD

**Issue by Tijmen34** [actions/download-artifact#219]
### What happened?

In the [documentation](https://github.com/actions/download-artifact/tree/v3#download-path-output) (and code), the output `download-path` is mentioned and can be used in steps after downloading the artifact. However, this is not directly specified in the action.yaml, which means an error is thrown when it is used together with a linter such as [actionlint](https://github.com/rhysd/actionlint). 

### What did you expect to happen?

I expect the output to be documented in the action.yaml, so linters understand that it is an existing variable to be used.

### How can we reproduce it?

Write the smallest workflow possible that contains this action and tries to use the output `download-path`.

```
steps:
- uses: actions/checkout@v3

- uses: actions/download-artifact@v3
  id: download
  with:
    name: 'my-artifact'
    path: path/to/artifacts

- name: 'Echo download path'
  run: echo ${{steps.download.outputs.download-path}}
```

Running [actionlint](https://github.com/rhysd/actionlint) will then throw an error, as it does not recognize the output as a valid variable.

### What version of the action are you using?

3.0.2

### What are your runner environments?

linux
