### ISSUE TITLE
Try out v2 Preview

### ISSUE THREAD

**Issue by konradpabjan** [actions/download-artifact#23]
The v2-preview of download-artifact is out and we need your help!

You can try it out by using `actions/download-artifact@v2-preview`
Any associated code and documentation can be found here: https://github.com/actions/download-artifact/tree/v2-preview

This issue is for general feedback and to report an bugs/issues during the preview

There is also a `v2-preview` of `upload-artifact`, see: https://github.com/actions/upload-artifact/issues/62

**Warning: At any time during the preview, there may be unannounced changes that can cause things to break. It is recommended not to use the preview of this action in critical workflows**

----

### Historical Context around v2-preview and v1

The `v1` versions of `download-artifact` (and `upload-artifact` ) are plugins that are executed by the runner. The code for `v1` can be found here: https://github.com/actions/runner/tree/master/src/Runner.Plugins/Artifact

The `v1` code is written in C# and is tightly coupled to the runner, it also uses special APIs that only the runner can use to interact with artifacts. If any changes or updates had to be made related to artifacts, they had to done on the runner and a new release had to roll out that would take a significant amount of time. With v2, there is no dependency on the runner so it will be much easier and faster to make changes and accept community contributions (right now it was pretty much impossible).

The `v2-preview` of download-artifact has been rewritten from scratch using Typescript with a new set of APIs that allow it interact with artifacts (previously only the runner could do this). There is a new NPM package called `@actions/artifact` that contains the core functionality to interact with artifacts (which this action uses for the most part). This NPM package is hosted in the `actions/toolkit` repo so anyone can use this to interact with artifacts when developing actions. You can find the package here (lots of documentation and extra info):
https://www.npmjs.com/package/@actions/artifact
https://github.com/actions/toolkit/tree/master/packages/artifact

### Further work

Since `v2-preview` is effectively a total rewrite from `v1`, There is a huge potential for bugs so it needs to be tested thoroughly before creating an actual `v2` release. We need help testing the core functionality which includes:
- Downloading a single artifact
- Downloading multiple artifacts at once

There will be no new features added as part of the `v2-preview`, we need to test the core functionality first and once a `v2` release is out, then we can start chipping away at issues/features that we have been unable to address with `v1`🙂 For the moment, please don't submit PRs for any new features to the `v2-preview` branch.

**Comment by spookyGh0st** [comment]
getting error `##[error]read ECONNRESET` when downloading a single artifact

my download  action

```yaml
      - name: get sirup.jar
        uses: actions/download-artifact@v2-preview
        with:
          name: sirup.jar
```

v1 works fine, only getting this error when using v2-preview.

**Comment by lovasoa** [comment]
Does the v2 solve https://github.com/actions/download-artifact/issues/11 ? It would be really nice to have the downloaded file path as the output of the action.

**Comment by konradpabjan** [comment]
I left a comment in the issue @lovasoa We can easily add the feature, though what do we do with the download file path if there are multiple artifacts being downloaded?

**Comment by konradpabjan** [comment]
I'm seeing some issues with the `v2-preview` (upload is going great, but download is having some problems). Working on an update

**Comment by CKGrafico** [comment]
Not sure if reported but in some point when I download an uploaded artifact all the txt files were converted to BINARY files, I solved using upload v2 but download v1, really strange.

```
      - name: Get the artifacts
        uses: actions/download-artifact@v2-preview
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./dotnetcorewebapp

```
now:
```
      - name: Get the artifacts
        uses: actions/download-artifact@v1
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./dotnetcorewebapp
```
