### ISSUE TITLE
[bug] Unable to download artifact(s): Artifact not found for name: <artifact-name>

### ISSUE THREAD

**Issue by IvanGithub-Professional** [actions/download-artifact#250]
### What happened?

So today, I ended up getting an error when trying to download a package within the same workflow. I properly name the artifact and the name parameter and it does not work. This only happens when I use the latest version.

Two examples using **master** and **v4**
```
    - name: Download Package
      uses: actions/download-artifact@master
      with:
        name: <artifact-name>
        path: ${{ env.REVISION_PACKAGE_PATH }}

    - name: Download Package
      uses: actions/download-artifact@v4
      with:
        name: <artifact-name>
        path: ${{ env.REVISION_PACKAGE_PATH }}
```

![image](https://github.com/actions/download-artifact/assets/38806447/96caccdb-d9f4-408d-9d04-61b062aa9203)
![image](https://github.com/actions/download-artifact/assets/38806447/cdcfad8e-9da3-4d05-a350-4a95958732c5)

### What did you expect to happen?

I expected it to find and download the artifact to the given path.

### How can we reproduce it?

To reproduce this, you simply use the latest version

### Anything else we need to know?

The workaround is to use **v3** instead of the latest version. I noticed a new release was published 5 hours ago

### What version of the action are you using?

v4

### What are your runner environments?

linux, window
