### ISSUE TITLE
download multiple files at once ?

### ISSUE THREAD

**Issue by medyagh** [actions/download-artifact#26]
could we download multiple folders at once ?

```
    - name: Download results 
      continue-on-error: true
      uses: actions/download-artifact@v1
      with:
        name: functional_test_docker_ubuntu
        name: barmetal_test_docker_ubuntu

```

? or do I have to repeat this block if I wanna download 8 folders?
