### ISSUE TITLE
[bug] Confusing log message with `pattern` and `merge-multiple`

### ISSUE THREAD

**Issue by bgilbert** [actions/download-artifact#262]
### What happened?

When downloading a set of artifacts with `pattern` and `merge-multiple`, the download proceeds as configured, but logs a confusing message:

```
Run actions/download-artifact@v4
/usr/bin/docker exec  9ffc04f292823f23fa864f42737e89dda32fde7a149c899b6f32ec39effecf8c sh -c "cat /etc/*release | grep ^ID"
No input name specified, downloading all artifacts. Extra directory with the artifact name will be created for each download
Found 47 artifact(s)
Filtering artifacts by pattern 'summary-*'
Preparing to download the following artifacts:
```

### What did you expect to happen?

The Action does not incorrectly report that it will download all artifacts, or that an extra directory will be created for each download.

### How can we reproduce it?

```
      - name: Download summaries
        uses: actions/download-artifact@v4
        with:
          pattern: "summary-*"
          path: summary
          merge-multiple: true
```

See the `Download summaries` step of [this run](https://github.com/bgilbert/openslide.github.io/actions/runs/7299422506/job/19892333296).

### What version of the action are you using?

v4.1.0

### What are your runner environments?

linux
