### ISSUE TITLE
Release Asset cannot be downloaded

### ISSUE THREAD

**Issue by GeluConstantin** [actions/download-artifact#290]
### What happened?

I used the action in the basic form. 

    - name: Download Assets
      uses: actions/download-artifact@v4

Got no errors but 0 Artifacts found. 

Run actions/download-artifact@v4
  with:
    merge-multiple: false
    repository: GeluKu/GitHub_Reference_for_Linux
    run-id: 77393133[2](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739313326/job/21101929231#step:5:2)[6](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739313326/job/21101929231#step:5:7)
No input name specified, downloading all artifacts. Extra directory with the artifact name will be created for each download
Found 0 artifact(s)
Total of 0 artifact(s) downloaded
Download artifact has finished successfully

### What did you expect to happen?

One Artifact should be downloaded.

This artifact is available over the API:
Run curl -L \
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4205  100  4205    0     0  10014      0 --:--:-- --:--:-- --:--:-- 10011
[
  {
    "url": "https://api.github.com/repos/GeluKu/GitHub_Reference_for_Linux/releases/139463539",
    "assets_url": "https://api.github.com/repos/GeluKu/GitHub_Reference_for_Linux/releases/139463539/assets",
    "upload_url": "https://uploads.github.com/repos/GeluKu/GitHub_Reference_for_Linux/releases/139463539/assets{?name,label}",
    "html_url": "https://github.com/GeluKu/GitHub_Reference_for_Linux/releases/tag/Automatic",
    "id": 139463539,
    "author": {
      "login": "github-actions[bot]",
      "id": 41[8](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739251057/job/21101724312#step:2:9)[9](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739251057/job/21101724312#step:2:10)8282,
      "node_id": "MDM6Qm90NDE4OTgyODI=",
      "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github-actions%5Bbot%5D",
      "html_url": "https://github.com/apps/github-actions",
      "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": false
    },
    "node_id": "RE_kwDOK2hahM4IUAtz",
    "tag_name": "Automatic",
    "target_commitish": "20eae4421b15f27e086a4a643cc6968ab3b02c22",
    "name": "Grafana V[10](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739251057/job/21101724312#step:2:11).3.1-1",
    "draft": false,
    "prerelease": false,
    "created_at": "2024-02-01T09:22:54Z",
    "published_at": "2024-02-01T09:31:32Z",
    "assets": [
      {
        "url": "https://api.github.com/repos/GeluKu/GitHub_Reference_for_Linux/releases/assets/149[13](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739251057/job/21101724312#step:2:14)9720",
        "id": [14](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739251057/job/21101724312#step:2:15)9139720,
        "node_id": "RA_kwDOK2hahM4I47EI",
        "name": "grafana-enterprise-10.3.1-1.x86_64.rpm",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/[15](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739251057/job/21101724312#step:2:16)368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/zip",
        "state": "uploaded",
        "size": 134,
        "download_count": 0,
        "created_at": "[20](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739251057/job/21101724312#step:2:21)[24](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739251057/job/21101724312#step:2:25)-02-01T09:[31](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739251057/job/21101724312#step:2:32):[32](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739251057/job/21101724312#step:2:33)Z",
        "updated_at": "2024-02-01T09:31:[33](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739251057/job/21101724312#step:2:34)Z",
        "browser_download_url": "https://github.com/GeluKu/GitHub_Reference_for_Linux/releases/download/Automatic/grafana-enterprise-10.3.1-1.x86_[64](https://github.com/GeluKu/GitHub_Reference_for_Linux/actions/runs/7739251057/job/21101724312#step:2:65).rpm"
      }
    ],
    "tarball_url": "https://api.github.com/repos/GeluKu/GitHub_Reference_for_Linux/tarball/Automatic",
    "zipball_url": "https://api.github.com/repos/GeluKu/GitHub_Reference_for_Linux/zipball/Automatic",
    "body": ""
  }
]

### How can we reproduce it?

Yes, logs available in the Repo: https://github.com/GeluKu/GitHub_Reference_for_Linux.git

### What version of the action are you using?

latest

### What are your runner environments?

linux

### Are you on GitHub Enterprise Server? If so, what version?

No

**Comment by TysonRayJones** [comment]
I may be having a similar problem - [my workflow](https://github.com/QTechTheory/QuESTlink/actions/runs/7680248325/job/20932072452) spontaneously broke sometime in the last 6 months

**Comment by Cogax** [comment]
Same issue here. Solved it by downgrading (using `@v2` instead of `@v4`).

**Comment by pdconant** [comment]
I think we're encountering the same issue. When we upload and download artifacts in the same GHA workflow, the download doesn't work. Uploading with `actions/upload-artifact@v3` works fine -- the artifact is found by later steps in the workflow. But if we use `actions/upload-artifact@v4`, the uploaded artifact isn't found (even though it shows up in the workflow results page). 

Here is a brief workflow that will illustrate the problem. 
```
name: GLUPAY-6911 Test
on:
  pull_request:
    branches: [ 'master' ]
    types: [ 'opened', 'synchronize' ]
    paths:
      - '.github/workflows/test.yml'
  workflow_dispatch:
    inputs:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest-4-cores
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Upload file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: workflow-file
          path: "./.github/workflows/test.yml"
          retention-days: 3
  download-artifact:
    runs-on: ubuntu-latest-4-cores
    needs: [ upload-artifact ]
    steps:
      - name: Download Single Artifact
        uses: actions/download-artifact@v3
        with:
          name: workflow-file
  download-artifacts:
    runs-on: ubuntu-latest-4-cores
    needs: [ upload-artifact ]
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
```

Everything works with `upload-artifact@v3`:
<img width="870" alt="Screenshot 2024-02-08 at 3 17 34 PM" src="https://github.com/actions/download-artifact/assets/77648436/32ce6468-3431-4105-92eb-efe01fd83154">

But the same workflow fails with `upload-artifact@v4`:
<img width="717" alt="Screenshot 2024-02-08 at 3 18 47 PM" src="https://github.com/actions/download-artifact/assets/77648436/34ccbf11-9c51-43e6-8769-e48862fc4b8d">
