### ISSUE TITLE
[bug] Downloading artifact from previous run (specifying its `run-id`) does not work

### ISSUE THREAD

**Issue by weinshec** [actions/download-artifact#295]
### What happened?

When specifying a `run-id` parameter to download an artifact from a previous workflow run (within the same repository) downloads the corresponding artifact of the current run, not the specified one (see screenshot)

![image](https://github.com/actions/download-artifact/assets/5006295/e951a5a9-6230-4620-b8b6-5dd314f9e3a5)

### What did you expect to happen?

The artifact from the specified `run-id` is being retrieved

### How can we reproduce it?

Use the action twice. First time with a specific `run-id`, the second time with the defaulted current `run-id`, e.g. 

```yaml
      - name: Download latest main artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: base-build-artifacts
          run-id: <previous run id>

      - name: Download current PR artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: new-build-artifacts
```

### What version of the action are you using?

v4

### What are your runner environments?

linux

**Comment by weinshec** [comment]
@croemheld, sorry for the confusion. Let me try to elaborate...

What the screenshot shows are 2 (consecutive) steps in my workflow that each attempt to download a (different) artifact

- The first one (titled: "_Download latest main artifact_") tries to download an artifact from the last time this workflow ran for a push-to-main event, hence I specify a concrete `run-id` from which the artifact should be downloaded (7840389011).
  ```yaml
   - name: Download latest main artifact
     uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: base-build-artifacts
        run-id: 7840389011
  ```
- The second step (titled: "_Download current PR artifact_") tries to download an artifact from the current run (7885661760), hence using the default run-id
  ```yaml
   - name: Download current PR artifacts
     uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: base-build-artifacts
        # no run-id specified here (defaults to current: 7885661760)
  ```
As a result, I expect both steps to download a **different** artifact (one from run 7840389011 and one from run 7885661760), but instead both steps seem to resolve the **same** artifact to download (artifact IDs are the same)
