### ISSUE TITLE
[bug] Problems with downloading artifacts with dot in the name

### ISSUE THREAD

**Issue by kenorb** [actions/download-artifact#296]
### What happened?

It's not possible to download artifacts with a dot in the name.

> Error: Unable to find any artifacts for the associated workflow

My artifact name is: `foo.bar`

These patterns doesn't work:

- `foo.ba?`
- `foo.ba*`
- `foo?ba*`

### What did you expect to happen?

Artifacts with dot in the name should be downloaded.

### How can we reproduce it?

```
jobs:

  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: foo.bar
          path: "*.*"

  download1:
    continue-on-error: true
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: foo.bar
          path: .

  download2:
    continue-on-error: true
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: foo.ba?
          path: .

  download3:
    continue-on-error: true
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: foo.ba*
          path: .

  download4:
    continue-on-error: true
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: foo?ba*
          path: .

  download5:
    continue-on-error: true
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: foo*ba?
          path: .

  download6:
    continue-on-error: true
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: foo*bar
          path: .

  download7:
    continue-on-error: true
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "*"
          path: .
```

Only download1 works, the other 2-7 doesn't work as expected.

### What version of the action are you using?

v4

### What are your runner environments?

linux
