### ISSUE TITLE
[bug] Matching names and merge-multiple causes data corruption

### ISSUE THREAD

**Issue by henryiii** [actions/download-artifact#298]
### What happened?

If multiple files have the same name, then download-artifact causes corrupts the files. This makes zip's unopenable (in one case) and sqlite files invalid (an a different repo). Making sure the names were unique fixed the problem.

### What did you expect to happen?

In both cases, I'd have been fine with an explicit error (matching names not allowed or something) - there should not have been matching files. There could also be a heuristic, like based on order or something, but I think that would tend to be more error prone than simply throwing a hard error and allowing the author to fix it.

### How can we reproduce it?

Upload files with the same names (ideally slightly different contents, I think), and then upload them to two separate artifacts, then download them and merge them with pattern and merge-multiple. The files should have corrupted data. (Once case was ~20 coverage files where the OS was not included in the name pattern, the other was Python wheels (module binaries) that were being produced on multiple variations of the same GHA image, probably also about 20 or so.

### Anything else we need to know?

https://github.com/wntrblm/nox/pull/772 was the coverage one with sqlite.

https://github.com/pypa/gh-action-pypi-publish/issues/215 is where the wheel one was mentioned.

### What version of the action are you using?

v4

### What are your runner environments?

linux

**Comment by FranciscoKnebel** [comment]
Coming from https://github.com/microsoft/playwright/issues/29451

With merge-multiple:
![image](https://github.com/actions/download-artifact/assets/10299622/89feb392-1b1c-41b3-897b-c3bc7d832fca)


Without merge-multiple:
 ```
    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: blob-reports-*
        path: all-blob-reports
    - name: Report Integrity check
      shell: bash
      run: |
        for file in all-blob-reports/*.zip; do
          unzip -t $file
        done
 ```

![image](https://github.com/actions/download-artifact/assets/10299622/f9666355-327e-488e-a306-5930b3034733)
