### ISSUE TITLE
[bug] Unable to download artifact(s): Unable to download and extract artifact: Request timeout

### ISSUE THREAD

**Issue by adrianimajion** [actions/download-artifact#300]
### What happened?

Starting at about 4:41 Pacific on 2/23, this action began reporting a timeout error when downloading an artifact uploaded in the previous job in the workflow. 

### What did you expect to happen?

This is our standard staging CI workflow and runs frequently throughout the day without issue, until this afternoon. I would expect artifacts to download as usual.

### How can we reproduce it?

Below is a reduced snippet of the relevant bits of our CI script, but I expect this is likely occurring with many/any use cases downloading an artifact. This artifact is <9mb in size. 

```
jobs:
   build:
    timeout-minutes: 30
    runs-on: ubuntu-small

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
       // generate something to upload here (our build script) 
      - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
      name: dist
      path: dist
   deploy: 
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

```

### Anything else we need to know?

This issue also occurred on @master.

I think my previous edit was mistaken, and this is actually fixed in V4 - verifying, and if that's the case I'll close this. 

### What version of the action are you using?

master, v3 

### What are your runner environments?

linux

### Are you on GitHub Enterprise Server? If so, what version?

No.
