### ISSUE TITLE
[bug] Artifact download failure on latest `master`

### ISSUE THREAD

**Issue by codebytere** [actions/download-artifact#302]
### What happened?

Actions failed to download artifacts using latest `master` of `actions/download-artifact` with the following errors:

```
##[debug]Failed to download artifact after 5 retries due to Callback called multiple times. Retrying in 5 seconds...
Error: Unable to download artifact(s): Unable to download and extract artifact: Artifact download failed after 5 retries.
##[debug]response.message: Artifact download failed: Blob storage chunk did not respond in 30000ms
##[debug]response.message: Artifact download failed: Blob storage chunk did not respond in 30000ms
##[debug]response.message: Artifact download failed: Blob storage chunk did not respond in 30000ms
##[debug]response.message: Artifact download failed: Blob storage chunk did not respond in 30000ms
##[debug]response.message: Artifact download failed: Blob storage chunk did not respond in 30000ms
##[debug]Node Action run completed with exit code 1
```

Rerunning does not solve the problem; it's a deterministic error.

### What did you expect to happen?

The workflow should download the artifact(s) without issues as expected.

### How can we reproduce it?

See https://github.com/electron/rbe-credential-helper/actions/runs/8046145660/job/21973168730 for sample failure. 

A simplified version of our workflow file:

```
name: Release

on:
  release:
    types: 
      - created

jobs:
  generate:
    name: Build
    strategy:
      matrix:
        include:
          - { runner: macos-latest, os: darwin, arch: arm64, cgo: '1' }
          - { runner: macos-latest, os: darwin, arch: amd64, cgo: '1' }
          - { runner: ubuntu-latest, os: linux, arch: arm64, cgo: '0' }
          - { runner: ubuntu-latest, os: linux, arch: amd64, cgo: '0' }
          - { runner: ubuntu-latest, os: windows, arch: amd64, cgo: '0' }
          - { runner: ubuntu-latest, os: windows, arch: arm64, cgo: '0' }
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Build
        run: go build -v -trimpath -buildvcs=false -o ./electron-rbe-credential-helper ./cmd/rbe-credential-helper
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: ${{ matrix.cgo }}
      - name: Archive
        run: tar -czvf electron-rbe-credential-helper-${{ matrix.os }}-${{ matrix.arch }}.tar.gz electron-rbe-credential-helper
      - uses: actions/upload-artifact@master
        with:
          name: electron-rbe-credential-helper-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          path: ./

  release:
    name: Release
    strategy:
      matrix:
        include:
          - { os: darwin, arch: arm64 }
          - { os: darwin, arch: amd64 }
          - { os: linux, arch: arm64 }
          - { os: linux, arch: amd64 }
          - { os: windows, arch: amd64 }
          - { os: windows, arch: arm64 }
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: generate
    steps:
      - uses: actions/download-artifact@master
        with:
          name: electron-rbe-credential-helper-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          path: ./
      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./electron-rbe-credential-helper-${{ matrix.os }}-${{ matrix.arch }}.tar.gz"
```

Full file can be found [here](https://github.com/electron/rbe-credential-helper/blob/main/.github/workflows/release.yml).

### Anything else we need to know?

I suspect that https://github.com/actions/download-artifact/pull/299 may have caused this. Switching from `actions/download-artifact@master` to `actions/download-artifact@v4` solved the problem immediately.

### What version of the action are you using?

`master`

### What are your runner environments?

linux
