### ISSUE TITLE
[bug](node:1591) [DEP0005] DeprecationWarning:

### ISSUE THREAD

**Issue by pinakighatak** [actions/download-artifact#327]
### What happened?

using @v4 creates the following warning:

`(node:1591) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use ``node --trace-deprecation ...`` to show where the warning was created)`

### What did you expect to happen?

if this is nodejs issue, it should be upgraded, to avoid issues.

### How can we reproduce it?

use this as normal, and it shows the error. I used it like this:
````yml
- name: Download Artifacts
  uses: actions/download-artifact@v4
  with:
    name: ${{github.run_number}}
    path: ${{github.run_number}}
````

### Anything else we need to know?

Running on ubuntu-latest

### What version of the action are you using?

v4

### What are your runner environments?

linux
