### ISSUE TITLE
[bug] Artifact download failed after 5 retries

### ISSUE THREAD

**Issue by marcosnr** [actions/download-artifact#339]
### What happened?

Using latest version, ids are the same in the same Workflow
```
    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: orgs_tfplan
        path: ./${{ env.ORG_STRUCTURE_PATH }}/orgs_tfplan
        retention-days: 8 
        if-no-files-found: error
        overwrite: true
```
logs for this are:
```
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Beginning upload of artifact content to blob storage
Uploaded bytes 9522
Finished uploading artifact content to blob storage!
SHA256 hash of uploaded artifact zip is 55f6d093abc9fb923b81a2215443eaa21f4fb6f3458f42c66af8f73135339b60
Finalizing artifact upload
Artifact orgs_tfplan.zip successfully finalized. Artifact ID 1658704995
Artifact orgs_tfplan has been successfully uploaded! Final size is 9522 bytes. Artifact ID is 1658704995
Artifact download URL: https://github.com/lokalise/infra-secops/actions/runs/9757819524/artifacts/1658704995
```
The next step tries to download it:
```
    - name: Download Terraform Plan Test
      id: download-plan
      uses: actions/download-artifact@v4
      with:
        name: orgs_tfplan
        path: ./${{ env.ORG_STRUCTURE_PATH }}/orgs_tfplan
```

Error: Unable to download artifact(s): Unable to download and extract artifact: Artifact download failed after 5 retries
Full log

```
Downloading single artifact
Preparing to download the following artifacts:
- orgs_tfplan (ID: 1658704995, Size: 9522)
Redirecting to blob download url: https://productionresultssa13.blob.core.windows.net/actions-results/9e701839-d365-4476-bc0e-2ab8b34ecb22/workflow-job-run-7e2501dc-18ab-5639-25c6-c45a87c8505c/artifacts/c123908d70f3d68b375b61d264a1acd0d4cb97713e9bbe063c8e900b1a12a769.zip
Starting download of artifact to: /home/runner/work/infra-secops/infra-secops/organization_structure/orgs_tfplan
(node:1794) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Unable to download artifact(s): Unable to download and extract artifact: Artifact download failed after 5 retries.

```

### What did you expect to happen?

The dowloaded artifact available at the given path

### How can we reproduce it?

Create a simple workflow :

```

jobs:
  terraform_check:
    name: 'Terraform Check PR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./${{ env.ORG_STRUCTURE_PATH }}

```

with steps above?

### What version of the action are you using?

 actions/download-artifact@v4

### What are your runner environments?

linux

**Comment by vignesh-gupta-xom** [comment]
It's a big issue for us as it's been used at enterprise level.

**Comment by brandtkeller** [comment]
Also experiencing the same problem - will investigate further.

**Comment by si-robinson** [comment]
Same here.  For now, we've pinned it to the previous version:
```uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e```

**Comment by maltesoerensen1337** [comment]
> Same here. For now, we've pinned it to the previous version: `uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e`

I'm getting the same error with that version.

But, in a different workflow that uses 4.1.8, it works:

> Run actions/download-artifact@v4.1.8
Downloading single artifact
Preparing to download the following artifacts:
- xxx (ID: xxx, Size: 916)
Redirecting to blob download url: https://productionresultssa11.blob.core.windows.net/actions-results/xxx
Starting download of artifact to: /home/runner/work/xxx
(node:1928) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Artifact download completed successfully.
Total of 1 artifact(s) downloaded
Download artifact has finished successfully

**Comment by maltesoerensen1337** [comment]
I was able to resolve my case and I have to admit it was avoidable ^^
The deprecation warning lead me on a wrong path.


When downloading the artifact, I specified the full filename instead of just the target directory. Changing that fixed the issue.

not working:
```
      - uses: actions/download-artifact@v4
        with:
          path: bpmn/my.bpmn
          name: bpmn-model
```

fixed:
```
      - uses: actions/download-artifact@v4
        with:
          path: bpmn
          name: bpmn-model
```

Hope this will help some of you others.
