### ISSUE TITLE
[bug] Creates a subdirectory named "artifact" under the specified path location

### ISSUE THREAD

**Issue by lnxpy** [actions/download-artifact#356]
### What happened?

This is my upload artifact step:

```yml
      - name: Upload badges as artifact
        uses: actions/upload-artifact@v3
        with:
          path: .pypi_chart/${{ matrix.package }}_badge.svg
```

and this is my download artifact step:

```yml
      - name: Download badges artifact
        uses: actions/download-artifact@v3
        with:
          path: .pypi_chart/
          merge-multiple: true
```

I expect all my .svg files to be stored under the `.pypi_chart/` directory like:

- `.pypi_chart/1.svg`
- `.pypi_chart/2.svg`
- `.pypi_chart/3.svg`

But it creates a subdirectory called `.pypi_chart/artifact/` and puts those svg files there.

### What did you expect to happen?

‍

### How can we reproduce it?

‍

### Anything else we need to know?

‍

### What version of the action are you using?

v4

### What are your runner environments?

linux
