### ISSUE TITLE
[bug] name config is not applied

### ISSUE THREAD

**Issue by serkonda7** [actions/download-artifact#368]
### What happened?

See here for the run: https://github.com/serkonda7/vscode-vba/actions/runs/8108302499/job/22161298658

I upload my artifact using
```
- name: Upload artifact
        # if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: vba.vsix
          path: vscode-vba-0.*.*.vsix
          if-no-files-found: error
```

And download it using
```
- name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vba.vsix
```

However `ls -R` shows this:
```
.:
vscode-vba-0.10.0.vsix
```

### What did you expect to happen?

The file name should be vba.vsix like I uploaded it.

### How can we reproduce it?

See above

### Anything else we need to know?

I'm not sure if the problem is the upload or download action, so this issue might be in the wrong repo.

### What version of the action are you using?

@4

### What are your runner environments?

linux
