### ISSUE TITLE
[bug] fails randomly without warning on ARM architecture

### ISSUE THREAD

**Issue by klaxalk** [actions/download-artifact#375]
### What happened?

In my pipeline, I am passing approx. 1GB of artifacts through several build jobs. When running on **ubuntu-24.04-arm**, the **actions/download-artifact@v4** job randomly fails without a warning or an error. It seems to be ok on the amd64 architecture.

Here is a minimal example: https://github.com/klaxalk/download_artifact_test/actions/runs/13136791298

![Image](https://github.com/user-attachments/assets/4c10ff7b-78a7-4e62-96ae-b361c7887bcc)

### What did you expect to happen?

I expect the artifacts to be downloaded and extracted normally.

### How can we reproduce it?

This repository contains a minimal example: https://github.com/klaxalk/download_artifact_test

```yaml
name: test

on:
  workflow_dispatch:

  push:
    branches:
      - "master"

jobs:

  init-artifacts:
    runs-on: ubuntu-24.04-arm
    steps:
      - id: init_artifacts
        run: |
          mkdir -p /tmp/artifacts
          head -c 1G /dev/urandom > /tmp/artifacts/large_file.txt
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: /tmp/artifacts/
          overwrite: true

  generate-jobs:
    needs: init-artifacts
    runs-on: ubuntu-24.04-arm
    outputs:
      packages: ${{ steps.generate.outputs.packages }}
    steps:
      - id: generate
        run: |
          echo "packages=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]" >> "$GITHUB_OUTPUT"

  build-job:
    needs: generate-jobs
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 360 # 6 hour timeout
    strategy:
      matrix:
        job: ${{ fromJson(needs.generate-jobs.outputs.packages) }}
      max-parallel: 1 # Run jobs serially
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts
          merge-multiple: true
          path: /tmp/artifacts/
      - id: add_artifact
        run: |
          touch /tmp/artifacts/${{ matrix.job }}
          ls /tmp/artifacts
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: /tmp/artifacts/
          overwrite: true

```

### Anything else we need to know?

- I tried adding delays before downloading the artifacts, did not help.
- Restarting failed jobs might succeed, but usually just moves the problem to a job running later in the line.

### What version of the action are you using?

v4

### What are your runner environments?

linux, Ubuntu 24.04, arm64

### Are you on GitHub Enterprise Server? If so, what version?

No, just the free/open version.
