### ISSUE TITLE
[bug] download may silently fail download, but not fail action

### ISSUE THREAD

**Issue by vholer** [actions/download-artifact#396]
### What happened?

When downloading multiple artifacts, one of the file could fail to download, but not failing the action as a whole. The workflow then continues and can lead in inconsitent result due to silent failure and missing files.

### What did you expect to happen?

If artifact fails to download, whole action must fail.

### How can we reproduce it?

IDK

### Anything else we need to know?

Snippet from GitHub Workflow:

```
....
  push:
    name: Push
    runs-on: ubuntu-22.04
    needs: [setup, build_test]
    timeout-minutes: 20
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Podman Login to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
...
```

Snippet from logs attached, but same warning as in #381, maybe it's related.

```
2025-03-27T18:35:32.3300700Z (node:1475) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2025-03-27T18:35:32.3305406Z (Use `node --trace-deprecation ...` to show where the warning was created)
```

[log.txt](https://github.com/user-attachments/files/19503977/log.txt)

### What version of the action are you using?

v4.2.1

### What are your runner environments?

linux

**Comment by michal-kralovic-vissim** [comment]
Hey, I'm experiencing the same issue with version 4.

The artifacts that downloaded correctly seem to have the following lines at the end:
```
SHA256 digest of downloaded artifact is (sha here)
Artifact download completed successfully.
Total of 1 artifact(s) downloaded
Download artifact has finished successfully
```
While the artifacts that don't seem to have downloaded correctly lack these lines, ending with:
```
(node:25916) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by michal-kralovic** [comment]
Hey, I'm currently experiencing the same issue with version 4. I haven't managed to find a concrete pattern in its behavior.

The artifacts that downloaded correctly seem to have the following lines at the end:
```
SHA256 digest of downloaded artifact is (sha here)
Artifact download completed successfully.
Total of 1 artifact(s) downloaded
Download artifact has finished successfully
```
While the artifacts that don't seem to have downloaded correctly lack these lines, ending with:
```
(node:25916) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by Kingdutch** [comment]
We're running into this as well and it seems that this issue was previously reported in #363. Alas no solution (or recognition of the issue) was added there.

**Comment by adrian-visnovsky-vissim** [comment]
Hey, we're running into this problem as well.

**Comment by patrick-rivos** [comment]
Is there any known workaround for this issue?

**Comment by adrian-visnovsky-vissim** [comment]
@patrick-rivos we just re-run our pipelines and it usually works fine the second time. Or you can download you artifact manually

**Comment by Kingdutch** [comment]
In our workflow I replaced the GitHub action with the `gh` CLI which uses a different implementation than the action. That's been working flawlessly from our testing thus far.

```
      - name: Download artifacts
        run: gh run download --repo "$GITHUB_REPOSITORY" "$GITHUB_RUN_ID"
        env:
          GH_TOKEN: ${{ github.token }}
```

**Comment by oenglund** [comment]
We are hitting this problem as well

**Comment by MattiasPernhult** [comment]
We are also hitting this problem

**Comment by fuzzlebuck** [comment]
Same issue, says it's downloaded, nothing downloaded.

**Comment by oto-macenauer-absa** [comment]
I also face the same issue. The `actions/download-artifact@v4` fails to provide all files from the artifact zip. It just silently fails with some files missing. The sha matches. The files can be downloaded manually. The `gh run download` workaround works.

**Comment by tiago-upbrasil** [comment]
My suspicion is that the bug occurs when the self-hosted server has a slow or bad Internet connection. This happens more when the download takes longer than usual.

**Comment by MED-26790** [comment]
Здравствуйте

**Comment by rhys-vdw** [comment]
We just had this as well, also in a self-hosted runner:

Download fails:
```
Downloading single artifact
Preparing to download the following artifacts:
- fmod-project-build-16795056208 [redacted]
Redirecting to blob download url: [redacted]
Starting download of artifact to: /Users/effortstarbuild/runner/_work/[redacted]
(node:19985) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

The final success messages are never posted (nor any errors) and the task succeeds:

<img width="471" height="165" alt="Image" src="https://github.com/user-attachments/assets/788f2b98-eaac-4439-8fa5-5fef5f5ac19e" />

Thankfully after re-running failed jobs we see the expected result:

```
Downloading single artifact
Preparing to download the following artifacts:
- fmod-project-build-16795056208 [redacted]
Redirecting to blob download url: [redacted]
Starting download of artifact to: /Users/effortstarbuild/runner/_work/[redacted]
(node:23030) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
SHA256 digest of downloaded artifact is [redacted]
Artifact download completed successfully.
Total of 1 artifact(s) downloaded
Download artifact has finished successfully
```

This is also with v4. 

```yml
      - name: Download FMOD build
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.fmod_build_artifact_id }}
          path: FmodProject/
```
