### ISSUE TITLE
Download fails with TF400898

### ISSUE THREAD

**Issue by petertiedemann** [actions/download-artifact#5]
I am playing around with upload and download of artifacts, and have so far not managed to perform a download, though the upload seems to succeed. Its very likely just me using it incorrectly, but error generated is not very clear to say the least:

![image](https://user-images.githubusercontent.com/1265354/63968107-3045c380-ca9f-11e9-950f-fe38bea0f5e9.png)

Here is one version of my workflow file causing this (as you might guess from the commented stuff, i have been trying a few different things):

```yaml
name: ASP.NET Core CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test -c Release --no-build
    - name: Publish with dotnet
      run: dotnet publish -c Release --no-build -o output
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: output
        path: output

  process:
    runs-on: windows-latest
    steps:
    - name: Mkdir
      run: mkdir output
    - name: Download
      uses: actions/download-artifact@master
      with:
        name: output
#        path: output

  #   - name: List download
  #     run: dir ./output
```

**Comment by TingluoHuang** [comment]
@petertiedemann 

try:

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    ....
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: output
        path: output

  process:
    runs-on: windows-latest
    needs: build
    steps:
    ....
    - name: Download
      uses: actions/download-artifact@master
      with:
        name: output
#        path: output
```

the `needs: build` will tells your `process` job to run after your `build` finish.

i think the problem you run into is your `process` job runs parallel with `build` job cause the artifact haven't uploaded when you try to download it.
