### ISSUE TITLE
Permission denied when downloading artifact

### ISSUE THREAD

**Issue by alexplischke** [actions/download-artifact#58]
We get the following permission denied error when trying to download the artifact from a previous job:
```
Run actions/download-artifact@v2
  with:
    name: saucectlbin
/usr/bin/docker exec  b3253aa2b26618a0d6b4b42a2899d7db08193dcc7a46c30efcd8dc18ad1f351f sh -c "cat /etc/*release | grep ^ID"
Starting download for saucectlbin
Directory structure has been setup for the artifact
Total number of files that will be downloaded: 1
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/__w/saucectl/saucectl/saucectl'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:294:12
    at FSReqCallback.oncomplete (fs.js:146:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/__w/saucectl/saucectl/saucectl'
}
```

Here's the job definition:
```
  puppeteer:
    needs: basic
    runs-on: ubuntu-latest
    container:
      image: saucelabs/stt-puppeteer-jest-node:v0.2.0

    steps:
      # appears that checkout@v2 uses javascript which is not compatible
      # with the included node version in the container image.
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Download saucectl binary
        uses: actions/download-artifact@v2
        with:
          name: saucectlbin

      - name: Workaround for container permissions
        run: |
          sudo chown -R $USER:$(id -gn $USER) /github/home

      - name: Run Sauce Pipeline Test
        run: |
          ./saucectl run -c ./.sauce/puppeteer.yml
        env:
          BUILD_ID: ${{ github.run_id }}

```

Link to pipeline: https://github.com/saucelabs/saucectl/runs/1004528103?check_suite_focus=true

Is there a workaround available? Is our setup wrong somewhere?
