### ISSUE TITLE
Feature request: wildcard support (or download-all)

### ISSUE THREAD

**Issue by StoneCypher** [actions/download-artifact#6]
One of the really useful things about uploading artifacts is caching logs, coverage reports, et cetera.  Those often have timestamps or UUIDs as names.

You can hack around it with a compression to a known name step, but, uploading and downloading artifacts by wildcard (or even just download-all) would be a huge benefit for post-processing, eg coverage merging

**Comment by DrSensor** [comment]
Just want to add a my use case for this :slightly_smiling_face: 
```yaml
build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [tmLanguage, sublime-syntax]
    steps:
    # ...several steps for producing an artifact
    - uses: actions/upload-artifact@master
      with: { name: '${{ matrix.target }}', path: dist }

publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@master
      with: { name: 'tmLanguage|sublime-syntax', path: dist }
    # ...several steps for publishing the artifacts
```
alternatively, maybe make the `name` field can accept array of string
```yaml
    - uses: actions/download-artifact@master
      with: { name: [tmLanguage, sublime-syntax], path: dist }
```

**Comment by marblenix** [comment]
alternatively it could mimic the run syntax for jobs.\<id\>.steps.shell

```yaml
      - name: Download build artifacts
        uses: actions/download-artifact@v1
        path: dist
        with: |
          foo1.zip
          foo2.zip
          foo3.zip
          foo4.zip
          foo5.zip
```

**Comment by datapythonista** [comment]
Would also find this very useful.

In my case I want to upload the logs of all failing jobs as artifacts. And in a last job that needs the rest to finish, I want to download all the `job_output_*` artifacts, and write the errors to a comment in the PR.

Having to upload/download all the outputs, and specify them manually in a step for each, makes the code much more complex and verbose than needed, and it's a big waste of resources.

**Comment by Frontear** [comment]
Agreed. My generated code uses versioning not accessible to the GitHub action configuration. Allowing for wildcard or even regex naming checks would make this significantly easier.

**Comment by dawnbass68** [comment]
Gosh
Thanks for your help I do appreciate it

**Comment by konradpabjan** [comment]
`v2-preview` is out and there is a new option that allows you to download all artifacts at once.

See the pinned issue for more information

**Comment by ElonH** [comment]
I hack the code and implement wildcard support (via RegExp).

https://github.com/ElonH/download-artifact-regexp

But sorry for my ugly code, it is not compatible with upstream.

**Comment by konradpabjan** [comment]
`download-artifact@v2` has been released so you can now download all artifacts at once.

It's not ideal (some users want a subset of artifacts instead of all of them), so I'll keep this issue open until we add wildcard support or something similar.

**Comment by fbidu** [comment]
Hello all! Hoping you're all safe in the middle of this - seemingly never ending pandemic.

I'm just passing by to bump this issue. I'm migrating a devops pipeline from Azure Pipeline to GitHub Actions and this is a crucial feature that's missing.

My use case is not new in itself - basically a job with a matrix strategy generates lots of files named `<random>.coverage`, then another job _should_ download all files named `*.coverage` into a folder and process them. This is something Azure supplies as [this `patterns` argument](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#arguments)

**Comment by TWiStErRob** [comment]
Hi there, newfound Actions fan here, just want to add my use case after upvoting all that I found above :)
 * multiple jobs in workflow, most of them publish an artifact (some of them are big or have many files)
 * jobs upload JUnit XML results
 * a job at the end that downloads said JUnit XMLs and generates a report

This last job unnecessarily downloads and extracts all artifacts, only to then ignore them with a pattern.

<details>
<summary>See it as YAML... [click]</summary>

```yaml
jobs:
  other-job1:
    steps:
      ...
      - uses: actions/upload-artifact@v2

  other-job2:
    steps:
      ...
      - uses: actions/upload-artifact@v2

  check:
    env:
      JOB_NAME: Run ${{ matrix.param1 }} on ${{ matrix.param2 }}
    steps:
      - ...
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ env.JOB_NAME }} Test Results XMLs
          path: ${{ github.workspace }}/**/build/test-results/test/TEST-*.xml
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ env.JOB_NAME }} Test Results HTMLs
          path: ${{ github.workspace }}/**/build/reports/tests/test/
    strategy:
      fail-fast: false
      matrix:
        include:
          - param1: 1
            param2: 2
          - param1: 3
            param2: 4

  publish-test-results:
    needs: check
    if: success() || failure()
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/* Test Results XMLs/**/*.xml
```
</details
