### ISSUE TITLE
The downloaded artifact should have the given ‘name’, not the original ‘path’ from actions/upload-artifact

### ISSUE THREAD

**Issue by leafac** [actions/download-artifact#82]
Here’s a workflow that demonstrates what I’m talking about: https://github.com/leafac/github-actions-download-artifact--name-issue/actions/runs/636138856

There’s a `producer` job that includes the following:

```yml
steps:
  - run: |
      echo TEST > file.txt
      tar -czf file.tgz file.txt
  - uses: actions/upload-artifact@v2
    with:
      name: a-different-name.tgz
      path: file.tgz
```

Then, a `consumer` job does the following:

```yml
steps:
  - uses: actions/download-artifact@v2
    with:
      name: a-different-name.tgz
  - run: |
      find .
      tar -xzf a-different-name.tgz
      find .
```

I expected the downloaded artifact to appear as `a-different-name.tgz`, which is the name I passed to `actions/download-artifact`, and is also the name that appears on the [Artifacts page](https://github.com/leafac/github-actions-download-artifact--name-issue/actions/runs/636138856#artifacts). Yet, surprisingly, the downloaded artifact appears as `file.tgz`.

I tried giving the `consumer` an explicit `path`, like the following:

```yml
steps:
  - uses: actions/download-artifact@v2
    with:
      name: a-different-name.tgz
      path: a-different-name.tgz
  - run: |
      find .
      tar -xzf a-different-name.tgz
      find .
```

But this doesn’t work either, I just end up with a file at `a-different-name.tgz/file.tgz`.
