### ISSUE TITLE
Download artifact from another repository

### ISSUE THREAD

**Issue by charliekang** [actions/download-artifact#83]
How do we download an artifact from another repository?
Or even another branch?

In gitlab:
```
needs:
  - project: ext_project\proj_name
    job: build
    ref: master
    artifacts: true
```
